porder order --name city_smaller_utm-wgs84_ghana --idlist /home/rave/cloud-free-planet/cfg/paper-aois/city_tile_ids_udm2.csv --item PSScene4Band --asset analytic_sr_udm2 --boundary /home/rave/cloud-free-planet/cfg/paper-aois/city-smaller-utm-wgs84.geojson --op clip email
porder order --name city_smaller_utm-wgs84_ghana --idlist /home/rave/cloud-free-planet/cfg/paper-aois/city_tile_ids.csv --item PSScene4Band --asset analytic_sr --boundary /home/rave/cloud-free-planet/cfg/paper-aois/city-smaller-utm-wgs84.geojson --op clip email
porder order --name ag_savanna_smaller_utm-wgs84_ghana --idlist /home/rave/cloud-free-planet/cfg/paper-aois/ag_savanna_tile_ids_udm2.csv --item PSScene4Band --asset analytic_sr_udm2 --boundary /home/rave/cloud-free-planet/cfg/paper-aois/ag-savanna-smaller-utm-wgs84.geojson --op clip email
porder order --name ag_savanna_smaller_utm-wgs84_ghana --idlist /home/rave/cloud-free-planet/cfg/paper-aois/ag_savanna_tile_ids.csv --item PSScene4Band --asset analytic_sr --boundary /home/rave/cloud-free-planet/cfg/paper-aois/ag-savanna-smaller-utm-wgs84.geojson --op clip email
porder order --name ag_forest_smaller_utm-wgs84_ghana --idlist /home/rave/cloud-free-planet/cfg/paper-aois/ag_forest_tile_ids_udm2.csv --item PSScene4Band --asset analytic_sr_udm2 --boundary /home/rave/cloud-free-planet/cfg/paper-aois/ag-forestry-smaller-utm-wgs84.geojson --op clip email
porder order --name ag_forest_smaller_utm-wgs84_ghana --idlist /home/rave/cloud-free-planet/cfg/paper-aois/ag_forest_tile_ids.csv --item PSScene4Band --asset analytic_sr --boundary /home/rave/cloud-free-planet/cfg/paper-aois/ag-forestry-smaller-utm-wgs84.geojson --op clip email
porder order --name forest_cleared_smaller_utm-wgs84_ghana --idlist /home/rave/cloud-free-planet/cfg/paper-aois/forest_cleared_tile_ids_udm2.csv --item PSScene4Band --asset analytic_sr_udm2 --boundary /home/rave/cloud-free-planet/cfg/paper-aois/forest-cleared-smaller-utm-wgs84.geojson --op clip email
porder order --name forest_cleared_smaller_utm-wgs84_ghana --idlist /home/rave/cloud-free-planet/cfg/paper-aois/forest_cleared_tile_ids.csv --item PSScene4Band --asset analytic_sr --boundary /home/rave/cloud-free-planet/cfg/paper-aois/forest-cleared-smaller-utm-wgs84.geojson --op clip email
porder order --name water_smaller_utm-wgs84_ghana --idlist /home/rave/cloud-free-planet/cfg/paper-aois/water_tile_ids_udm2.csv --item PSScene4Band --asset analytic_sr_udm2 --boundary /home/rave/cloud-free-planet/cfg/paper-aois/water-smaller-utm-wgs84.geojson --op clip email
porder order --name water_smaller_utm-wgs84_ghana --idlist /home/rave/cloud-free-planet/cfg/paper-aois/water_tile_ids.csv --item PSScene4Band --asset analytic_sr --boundary /home/rave/cloud-free-planet/cfg/paper-aois/water-smaller-utm-wgs84.geojson --op clip email

