---
title: "Create f pool"
author: "Lei Song"
date: "7/31/2018"
output: 
  html_document:
    theme: united
    number_sections: true 
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Get the interaction of AQIs and master grid

```{r aoi, message=FALSE, warning=FALSE, eval = TRUE}
library(sf)
library(raster)
library(DBI)
library(dplyr)
library(rmapaccuracy)

## Read AOIs
aois <- st_read("spatial/data/processed/image_target_aois.geojson")
## Read master grid
master_grid <- raster("spatial/data/processed/master_grid.tif", band = 1)

## Extract the ids of master grid of AOIs
aois$id <- 1:nrow(aois)
aois_grid <- extract(master_grid, aois, df = TRUE, weights = TRUE)
# aois_grid <- mask(master_grid, aois)
# aois_grid <- getValues(aois_grid)
# aois_grid <- aois_grid[complete.cases(aois_grid)]
grids <- paste0("'", aois_grid$master_grid, "'", collapse = ",")
```

```{r, eval = FALSE, echo = FALSE}
# check new spatial query method against original
library(rmapaccuracy)
coninfo <- mapper_connect(user = pgupw$user, password = pgupw$password,
                          db.tester.name = "lestes", host = "crowdmapper.org")
sql_str <- "SELECT id from master_grid WHERE avail='F'"
fids <- DBI::dbGetQuery(conn = coninfo$con, statement = sql_str)
all(aois_grid$master_grid %in% fids$id)
all(fids$id %in% aois_grid$master_grid)
```


## Update the master_grid table

```{r update_master_grid, message=FALSE, warning=FALSE, eval = TRUE}
library(rmapaccuracy)
coninfo <- mapper_connect(user = pgupw$user, password = pgupw$password,
                          db.tester.name = "lestes", host = "crowdmapper.org")
sql_str <- paste0("UPDATE master_grid SET avail='F' WHERE id in (", grids, ")")
dbExecute(coninfo$con, sql_str)
```

## Make the csv file for cvml
```{r csv, message=FALSE, warning=FALSE, eval = TRUE}
library(aws.s3)
coors <- coninfo$con %>% tbl("master_grid") %>% filter(id %in% aois_grid) %>% 
  select(x, y, name) %>% collect()
r <- rmapaccuracy:::dummy_raster()
rowcol <- cbind("name" = coors$name, 
                rmapaccuracy:::rowcol_from_xy(r, x = coors$x, y = coors$y))
name_col_row <- lapply(c(1:nrow(rowcol)), function(x) {
        paste0(rowcol[x, 1], "_", rowcol[x, 2], "_", rowcol[x, 3])
})
result <- cbind(rowcol, name_col_row)

############### Scrub this from git!!!! Read this in from untracked 
# configuration file
Sys.setenv("AWS_ACCESS_KEY_ID" = "AKIAIA5K2SM5DPW52PYA",
               "AWS_SECRET_ACCESS_KEY" = "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",
               "AWS_DEFAULT_REGION" = "us-east-1")
###########################

localfile <- paste0(coninfo$dinfo[2], "/spatial/data/processed/f_pool.csv")
write.csv(result, localfile, row.names = F)
put_object(file = localfile, object = "s3://activemapper/f_pool.csv")
file.remove(localfile)
```



