mapper:
    DEBUG: True
    # Key connection parameters.
    db_production_name: 
    db_sandbox_name: 
    db_username: 
    db_password: 
    db_url: 
    db_host: 
    # GitHub user maphelp's token
    github_token: 
    github_repo: 
    # Flask Mail Settings
    MAIL_SERVER: 
    MAIL_PORT: 
    MAIL_USE_SSL: 
    MAIL_USE_TLS: 
    MAIL_USERNAME: 
    MAIL_PASSWORD: 

    # Planet Settings
    PL_API_KEY: 

cvml:
    aws_access: 
    aws_secret: 
    aws_region: 
