mapper:
    DEBUG: 
    SECRET_KEY: 
    # Key connection parameters.
    db_production_name: 
    db_sandbox_name: 
    db_username: 
    db_password: 
    db_url: 
    db_host: 
    # GitHub user maphelp's token
    github_token: 
    github_repo: 
    # Flask Mail Settings
    MAIL_SERVER: 
    MAIL_PORT: 
    MAIL_USE_SSL: 
    MAIL_USE_TLS: 
    MAIL_USERNAME: 
    MAIL_PASSWORD: 

    # Planet Settings
    PL_API_KEY:

    # s3 connection params
    aws_access:
    aws_secret:
    aws_region:
 

cvml:
    # s3 params
    prefix: planet
    pool: f_pool_ZA.csv
    incoming_names: incoming_names_ZA.csv
    #currently needs prefix can be changed to use same "prefix" param above
    image_catalog: planet-test/planet_catalog.csv
    image_output_pattern: s3://azavea-africa-test/images/image_c{}_r{}.tif
    outgoing: s3://azavea-africa-test/tmp/outgoing_names.csv
 
