ALTER USER postgres WITH PASSWORD 'Afr1c@';

-- Role: ***REMOVED***
-- DROP ROLE ***REMOVED***;
CREATE ROLE ***REMOVED*** LOGIN
  SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;
ALTER USER ***REMOVED*** WITH PASSWORD '***REMOVED***';
